//Operadores aritméticos +, -, *, /, %
2 + 2;
8 - 3;
4 * 5;
9 / 3;
7 % 2; //resto da divisão


//Operadores de atribuição +=, -=, *=, /=, %=.
result += 2;
result -= 5;
result *= 8;
result /= 2;
result %= 6;

//Operadores de incremento e decremento ++ e --
result++; //pós incremento
++result; //pré incremento
result--;
--result;

//Operador binários |, &, ^, ~, <<, >> e >>>
4 | 3; 
3 & 1;
5 ^ 2;
~2;
4 << 2;
128 >> 1;
-2 >>> 1;

//não confundir | com || e & com &&. (com 2 caracteres são para boolean)