//Os primitivos são imutáveis, ou seja, ao longo do tempo seu valor não é alterado.
//digitar no terminal 'Node'. typeof define o tipo do dado.

typeof 10;                            //number
typeof "JavaScript";                  //string
typeof true;                          //boolean
typeof Symbol("iterator");            //symbol
typeof null;                          //object
typeof undefined;                     //undefined
typeof function sum(a,b){return a+b}; //function
typeof {name:'Leo'};                  //object
typeof [1,2,3,4,5,6];                 //object
typeof /[a-zA-Z_$]/;                  //object
typeof new Date();                    //object
